FROM node:16-alpine as build

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm run install:frontend
COPY . ./
RUN npm run build:frontend

# Stage - Production
FROM nginx:1.22-alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]