version: "3"
services:
  frontend:
    image: beergamelfh/beergame-frontend:latest
    ports:
      - "8080:80"

  backend:
    image: beergamelfh/beergame-backend:latest
    environment:
      # Port on which the backend is listening
      - SERVER_PORT="3001"

      # Cross Origin Resource Sharing Origin
      - SERVER_CORS_ORIGIN="beergame.example.de" # allow only this domain as frontend

      # Connection string for connecting to local or external database. Keep it secret!
      - MONGOOSE_CONNECTIONSTRING="mongodb://admin:example@mongo:27017"
    ports:
      - "3001:3001"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: