version: "3"
services:
  frontend:
    container_name: frontend-prod
    image: beergame/frontend:latest-prod
    environment:
      # Not working now, environment variables not passed to React
      # default is "http://localhost:3001"
      - REACT_APP_BACKEND_URL=${BE_URL:-http://localhost:3001}
    build:
      context: ../client
      dockerfile: Dockerfile-Production
    ports:
      - 80:80

  backend:
    container_name: backend
    image: beergame/backend:latest
    build:
      context: ../server
      dockerfile: Dockerfile
    environment:
      # Cross Origin Resource Sharing Origin, allow only this domain as frontend
      - SERVER_CORS_ORIGIN=${FE_URL:-*}
      # Connection string for connecting to local or external database. Keep it secret!
      - MONGOOSE_CONNECTIONSTRING=${MONGO_STRING:-"mongodb://admin:example@mongo:27017"}
    ports:
      - 3001:3001

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-example}
    #    ports:
    #      - 27017:27017
    volumes:
      - mongodb-data-dev:/data/db

volumes:
  mongodb-data-dev: