# Diese Datei ermöglicht das lokale Ausführen vom Beergame Projekt über die Öffentlichen Images des aktuellen Releases. Dafür ist keine lokale Kopie des Github Repositories nötig.

version: "3"
services:
  frontend:
    container_name: frontend-dev
    image: beergamelfh/beergame-frontend:dev-latest
    environment:
      # default is "http://localhost:3001"
      - REACT_APP_BACKEND_URL=${BE_URL:-http://localhost:3001}
    ports:
      - 3000:3000

  backend:
    container_name: backend
    image: beergamelfh/beergame-backend:latest
    environment:
      # Cross Origin Resource Sharing Origin, allow only this domain as frontend
      - SERVER_CORS_ORIGIN=${FE_URL:-*}
      # Connection string for connecting to local or external database. Keep it secret!
      - MONGOOSE_CONNECTIONSTRING=${MONGO_STRING:-"mongodb://admin:example@mongo:27017"}
    ports:
      - 3001:3001

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      # Default credentials: admin:example
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-example}
    #    ports:
    #      - 27017:27017
    volumes:
      - mongodb-data-dev:/data/db

volumes:
  mongodb-data-dev: