# This is a basic workflow to help you get started with Actions
name: CI-CD - Frontend - Dev

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
 # pull_request:
 #   branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  ###################################################################
  # Warning: There is no check, whether this build is working or not!
  ###################################################################

  push_to_Docker_Hub:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      # build docker image and push to docker hub
      # only if the app build and test successfully

      steps:
        - name: checkout repo
          uses: actions/checkout@main

        - name: Set up QEMU
          uses: docker/setup-qemu-action@master
      
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@master

        - name: Login to DockerHub
          uses: docker/login-action@master
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      
        - name: Build and push
          uses: docker/build-push-action@master
          with:
            context: ./client/
            file: ./client/Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/beergame-frontend:dev-latest,  ${{ secrets.DOCKERHUB_USERNAME }}/beergame-frontend:1.${{ github.run_number }}-dev